--menage  FIXE - POST S42-2024

--MENU FIXE_MENU_HNO_GP

--Menage CHOIX RESILIE_DISSUASION_DEXTER  
delete  from MAC_CHOIX where CHOIX_NOM ='RESILIE_DISSUASION_DEXTER' 
and MENU_ID = (select MENU_ID from MAC_MENU where MENU_NOM ='FIXE_RESILIE_DISSUASION_DEXTER' and  APP_ID = (select APP_ID from MAC_APPLICATION where APPLI='FIXE'));

--Menage MENU  FIXE_RESILIE_DISSUASION_DEXTER
delete  from MAC_MENU where MENU_ID = (select MENU_ID from MAC_MENU where MENU_NOM ='FIXE_RESILIE_DISSUASION_DEXTER' and  APP_ID = (select APP_ID from MAC_APPLICATION where APPLI='FIXE'));


--Menage CHOIX RESILIE_DISSUASION_SEARCH  
delete  from MAC_CHOIX where CHOIX_NOM ='RESILIE_DISSUASION_SEARCH' 
and MENU_ID = (select MENU_ID from MAC_MENU where MENU_NOM ='FIXE_RESILIE_DISSUASION_SEARCH' and  APP_ID = (select APP_ID from MAC_APPLICATION where APPLI='FIXE'));

--Menage MENU  FIXE_RESILIE_DISSUASION_SEARCH
delete  from MAC_MENU where MENU_ID = (select MENU_ID from MAC_MENU where MENU_NOM ='FIXE_RESILIE_DISSUASION_SEARCH' and  APP_ID = (select APP_ID from MAC_APPLICATION where APPLI='FIXE'));

commit;

